### ISSUE TITLE
Instruct docopt to use stdin by default

### ISSUE THREAD

**Issue by thedrow** [docopt/docopt#150]
Is there a way to instruct docopt to use the stdin by default for a file argument?
If not, it should be added.

**Comment by mentalisttraceur** [comment]
It seems that there was a misunderstanding in play here that no one addressed: @thedrow seemed to think that `docopt` was specially handling `/dev/stdin`. So to clarify: `docopt` is just treating `/dev/stdin` as any other default argument string. It's just that on typical Linux setups, `/dev/stdin` exists on the file system, and magically resolves for each process opening it to its own standard input.
