### ISSUE TITLE
Allow to strip dashes from options in result dictionary

### ISSUE THREAD

**Issue by pavel-paulau** [docopt/docopt#225]
From the project README:

> The return value is a simple dictionary with options, arguments and commands as keys, spelled exactly like in your help message.

`options['--file']` looks too odd though. That would be great if a user could invoke docopt with additional named parameter:

```
options = docopt(__doc__, strip_dashes=True)
```

So that result dictionary has no leading dashes, which is equivalent to:

```
def strip_dashes(options):
    return {k.lstrip('-'): v for k, v in options.items()}

options = strip_dashes(docopt(__doc__))
```

Will you accept pull request for this feature?

**Comment by InfernoZeus** [comment]
Had the same issue. I'm using this one liner:
`args = {arg.lstrip('-') : value for arg, value in docopt(__doc__).items()}`

Coming back to post it here, I realised @pavel-paulau has basically the same thing in his original post.
