### ISSUE TITLE
Feature Request: Support for @FILE CLI Option for Additional CLI Options

### ISSUE THREAD

**Issue by calebwherry** [docopt/docopt#242]
I [created a StackOverflow question](http://stackoverflow.com/q/27427555/408160) and got no hits on it. I also have looked through all the documentation and can't find anything on it so I am putting in a feature request.

In some command line applications, there is the ability to use the @FILE syntax to include a file that contains more CLI options. This is especially useful for apps like `ar` when you could potentially run into the max length of a command line call.

I use DocOpt.cpp so I would most likely port this over to that if it gets approved. I wanted to post it here to get people's feedback on if it is something everyone agrees is a good addition to DocOpt.

**Comment by ptman** [comment]
I would also like to have some support for reading flags from file like [gflags](https://github.com/gflags/python-gflags/blob/master/gflags.py#L123). Any syntax is most likely ok

**Comment by thejcannon** [comment]
Any updates on this issue?
FWIW it also matches the [`argparse` `fromfile_prefix_chars` option](https://docs.python.org/3/library/argparse.html#fromfile-prefix-chars) and might be the only thing stopping us from switching over our `argparse`-heavy utility to using `docopt`
