### ISSUE TITLE
Two long options can result in "specified ambiguously" error (Javascript)

### ISSUE THREAD

**Issue by mmastrac** [docopt/docopt#248]
When I specify --woff given the following two option definitions, I get an error saying that --woff was specified ambiguously. 

  --woff2=<mode>      Processing mode for woff2 fonts: data, link or omit [default: omit]
  --woff=<mode>       Processing mode for woff fonts: data, link or omit [default: data]

Is this by design?

**Comment by keleshev** [comment]
Oh, didn't notice this is JS. This issue should be moved to docopt/docopt.coffee repo. /cc @sonwell
