### ISSUE TITLE
Which docopt branch contains the latest published code?

### ISSUE THREAD

**Issue by voieducode** [docopt/docopt#250]
Hi, I recently realised that master does not contain the latest published code. Which branch should I use as the reference to bring the .NET port up to speed with the python reference implementation?

**Comment by keleshev** [comment]
That would be tag 0.6.2. Master branch contains some experimental stuff that I am not happy about. However, it is already in master, so I don't want to force-push 0.6.2 into it.

**Comment by voieducode** [comment]
Ok so do you recommend that I get in sync with 0.6.2? It looks like I have
your experimental changes in my master branch.

**Comment by keleshev** [comment]
:+1:
