### ISSUE TITLE
My docopt port is based on master branch. Should I be concerned?

### ISSUE THREAD

**Issue by BlaXpirit** [docopt/docopt#252]
My port of docopt to a different language is directly based on code from master branch of docopt.py. Are there any problems with this and what can be done to fix them?

**Comment by keleshev** [comment]
I'm not sure if current master is going in the right direction, so it may be a problem. It's best to base your work of [0.6.2](https://github.com/docopt/docopt/tree/0.6.2) tag. However, 0.6.2 and master are not that different. The only serious difference I can remember is how options-section is handled. In `0.6.2` any line starting with `-` can denote an option. And in `master` it should be inside a paragraph that starts as `.*options:`.
