### ISSUE TITLE
Port of docopt to Nim

### ISSUE THREAD

**Issue by BlaXpirit** [docopt/docopt#253]
I have ported *docopt* to [Nim programming language](http://nim-lang.org/):

https://github.com/BlaXpirit/docopt.nim

174/174 tests pass.

I would like to move this to docopt organization.

**Comment by keleshev** [comment]
Sorry for taking so long. I just added you to the `docopt` team. Now you can move your repository (go to Settings of your repository).

Welcome to the club!
