### ISSUE TITLE
Capitalized required arguments return the argument passed in instead of True/False

### ISSUE THREAD

**Issue by SamuelRazzell** [docopt/docopt#255]
I'm not sure if this is intended behavior or not but with this code:

```
"""Usage:
	test DFU
	test dfu
"""
from docopt import docopt
print docopt(__doc__)
```

You will see the dictionary come back as 
```
python test.py DFU
    {'DFU': 'DFU',
    'dfu': False}
python test.py dfu
    {'DFU': 'dfu',
    'dfu': False}
```

If this is supposed to happen, that's fine, but I couldn't find any documentation on the fact that an all capitalized word returns the arguments instead of a True/False.

I'm kind of curious as to why this happens, so I reading through the source, but I figured I should ask about it so that other people can see what's going on.

**Comment by keleshev** [comment]
Capitalizing words are treated as positional arguments, like `<dfu>`. So your usage corresponds to:
```
Usage:
    test <dfu>
    test dfu
```

The docs say:

> * `<arguments>`, `ARGUMENTS`. Arguments are specified as either upper-case words, e.g. my_program.py CONTENT-PATH or words surrounded by angular brackets: my_program.py <content-path>.

**Comment by SamuelRazzell** [comment]
Ah, ok. Cool. I was searching for 'capitalize' and 'all caps' so I didn't see the part about upper-case. Thanks!
