### ISSUE TITLE
identical doc string succeeds on MacOSX fails on Linux and in Browser with 0.6.1

### ISSUE THREAD

**Issue by harijay** [docopt/docopt#256]
I have a simple usage message
Note the space between the run1 and the f.

```
Usage: MegaMPFileTraverseDM.py \<SampleSheet.csv\> \<run1 f\> \<run2f\> \<index1f\> \<index2f\>\<output_dir_root\>
```

This parses the invocation below fine and succeeds on MacOSX running python 2.7.6 and docopt 0.6.1
Trying this invocation command on Linux or on the try.docopt.org fails and returns the usage message.  
I am trying to understand why this does not consistently succeed. All are running the same 0.6.1 version of docopt

```
 python MegaMPFileTraverseDM.py ~/miseqdata/SampleSheetTemplateTest.csv smalltest/run1_aa_baby_R1_split.fastq.gz smalltest/run2_aa_baby_R2_split.fastq.gz smalltest/index1_aa_baby_I1_split.fastq.gz smalltest/index2_aa_baby_I2_split.fastq.gz  smalltest
```

If I remove the space between the run1 and the f , then it succeeds regardless of the OS. This is just a representative example, in reality my option is a lot longer and shows a more descriptive usage message that only succeeds on OSX.

**Comment by keleshev** [comment]
The feature of having spaces inside `<arg>` style arguments is an experimental feature that only exists in master branch, the tagged 0.6.1 release does not support this. That means that on your Mac you probably installed a pre-release version directly from GitHub, and not from PyPI.
