### ISSUE TITLE
Arguments grouped by command

### ISSUE THREAD

**Issue by Xumeiquer** [docopt/docopt#257]
Hi,

I am working with the library and I come up with it does not recognize what arguments were passed through each command.

I have the following code:
```Python
from docopt import docopt

__doc__ = """
Usage:
    test (cmdA (--all | [options]) | cmdB (--all | [options]))...

Options:
    -i, --input
    -o, --output
"""

args = docopt(__doc__)
print(args)
```

When I execute this code with the folloing command line
```
python test.py cmdA --all cmdB --input
```
I got the following output from the docopt
```Python
{'--all': 1,
 '--input': 1,
 '--output': 0,
 'cmdA': 1,
 'cmdB': 1}
```
According to this output I am not able to know whether `--all` argument belogns to `cmdA` or `cmdB`, and the same thing happens with the options. I am not able to recognize whether the arguument `--input` belogns to `cmdA` or `cmdB`.

A possible solution could be something like:
* Adding a dictionary for each command with its arguments
* Adding a empty dictionary if the command was called without arguments
* If the command wasn't called then set it to None

For example:
```Python
{'cmdA': {
    '--input': 0,
    '--all': 1,
    '--output': 0},
'cmdB': {
     '--input': 1,
     '--all': 0,
     '--output': 0}
}
```

I hope this helps.

Thank you.

**Comment by keleshev** [comment]
Such feature would be quite a stretch for docopt. Don't forget that shell programs are like functions, and their parameters are like Python's args and kwargs. No one is coming to Guido and asks him to allow function invocations like `function('cmdA', all=True, 'cmdB', all=True)` to succeed. Allowing things like this is what leads to Perl, PHP, and JavaScript madness. Docopt is designed to limit the amount of madness that is possible with shell programs.
