### ISSUE TITLE
Can't have blank line between option descriptions.

### ISSUE THREAD

**Issue by kalekundert** [docopt/docopt#259]
I think it is a bug that docopt stops parsing options as soon as it encounters a blank line.  This precludes giving detailed option descriptions in the way most man pages do.  For example:

```python
from docopt import docopt

print(docopt("""\
Usage:
    bug.py [options]

Options:
  -f --foo <foo>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam justo sem, 
        malesuada ut ultricies ac, bibendum eu neque. Lorem ipsum dolor sit 
        amet, consectetur adipiscing elit.

  -b --bar <bar>
        Aenean at tellus ut velit dignissim tincidunt. Curabitur euismod 
        laoreet orci semper dignissim. Suspendisse potenti. Vivamus sed enim 
        quis dui pulvinar pharetra.
"""))

# {'--foo': None}
```

The --bar option is not parsed because the options section ends when docopt encounters the first blank line, which it does after the --foo description.  This is contrary to the documentation, which states that "every line in doc that starts with - or -- (not counting spaces) is treated as an option description".

I did a git bisect and found that this behaviour was introduced in commit d5b96f878, which was meant to address #102.  I can get my example to work by adding a space to the blank line between --foo and --bar, but that's a hack.

After reading #250, I realized that this problem is not in the most recent release (0.6.2).  So this isn't a pressing problem for me any more, because I can just use 0.6.2 instead of master.  But I still think a test should be added to make sure cases like the one above are allowed.

**Comment by keleshev** [comment]
This is should be present only in current master, but not on the latest PyPI release. Treat current master as experimental and unstable, only tagged versions (which are also PyPI releases) are stable.
