### ISSUE TITLE
Why use split here

### ISSUE THREAD

**Issue by psykzz** [docopt/docopt#263]
https://github.com/docopt/docopt/blob/master/examples/git/git.py#L48 
Why not just use a list to start with?

**Comment by keleshev** [comment]
Because that's less to type. Compare:

```python
'checkout clone commit push remote'.split()
['checkout', 'clone', 'commit', 'push', 'remote']
```

Also, easier to read, I think.

**Comment by keleshev** [comment]
I want to add that I'm glad that you asked this questions, and that everyone who has more questions about the code are welcome to ask them here.
