### ISSUE TITLE
DocoptExit is raised when - in windows - a script is called without "python"

### ISSUE THREAD

**Issue by sentriz** [docopt/docopt#266]
my_script.py:

``` python
"""
Usage:
  my_script.py  (<url> | --artist=<name> --album=<name>)
                [--do-this | --do-that] [--folder=<name>]
  my_script.py  (--help | --version)
"""

from docopt import docopt

arguments = docopt(__doc__)
print(arguments)
```
## 

running `python my_script.py http://example.com --do-this` from the Windows command line returns:

```
{'--album': None,
 '--artist': None,
 '--do-that': False,
 '--do-this': True,
 '--folder': None,
 '--help': False,
 '--version': False,
 '<url>': 'http://example.com'}
```

which is absolutely fine.
## 

however, running `my_script.py http://example.com --do-this` returns:

```
Usage:
  my_script.py  (<url> | --artist=<name> --album=<name>)
                [--do-this | --do-that] [--folder=<name>]
  my_script.py  (--help | --version)
```

which is not.
## 

is this a docopt or Windows issue?

**Comment by keleshev** [comment]
Interesting. I don't have immediate access to a Windows machine, so I can't figure it out right now. I suspect something unexpected is with `sys.argv`. Can you print it out in both cases?

**Comment by sentriz** [comment]
sure..  
when running `python my_script.py http://example.com --do-this`:
sys.argv is: `['my_script.py', 'http://example.com', '--do-this']`

when running `my_script.py http://example.com --do-this`:
sys.argv is: `['M:\\dev\\temp_env\\my_script.py']` - the path to `my_script.py`

**Comment by BlaXpirit** [comment]
Obviously something is wrong with your *.py* type association (or maybe it was never supposed to work like this on Windows).

If `argv` is not populated, this is not a problem with *docopt*.

**Comment by sentriz** [comment]
yes, you're right. I didn't see until @keleshev  asked me to check `argv`.

**Comment by keleshev** [comment]
Maybe anyone on @docopt team knows enough Windows to tell us why `argv` is "empty" in the second case?

**Comment by BlaXpirit** [comment]
I just tried some things on my virtual machine. No matter what I do, I get the same behavior/problem. Even if it is possible to get the type association to work right, the defaults seem to be broken.

**Comment by sentriz** [comment]
hmm, it seems not much can be done by docopt here then.
