### ISSUE TITLE
Outdated "Porting docopt to other languages"

### ISSUE THREAD

**Issue by ReneSac** [docopt/docopt#269]
There is a section in the  README.rst called "Porting docopt to other languages". It presents an incomplete list of only 4 ports like they are all the ports. Either complete the list, remove or put a link to a complete list of ports.

**Comment by keleshev** [comment]
Thanks for pointing out. Pull-request is welcome.

**Comment by ReneSac** [comment]
Which of the three solutions is preferred?

**Comment by keleshev** [comment]
Link to docopt organization is probably best.
