### ISSUE TITLE
Allow newline between options for better readability

### ISSUE THREAD

**Issue by egalitarian** [docopt/docopt#271]
```
"""Usage:
  test.py [options]

Options:
  -h --help              show this help message and exit

  --filetypes            list all supported input filetypes
"""

from docopt import docopt
arguments = docopt(__doc__, version='3.0.0dev1')
print arguments
```

Testing the code above:
```
python test.py --filetypes
```
results in displaying the usage and exiting. If the newline separating --help and --filetypes is removed than all is well and --filetypes is found in the docopt dictionary.

Sometimes when having lots and lots of options it's better to group them together by leaving a newline between the groups.
```

**Comment by keleshev** [comment]
The tagged 0.6.2 version should allow that. `master` has experimental changes.

**Comment by egalitarian** [comment]
Great. Thanks.
