### ISSUE TITLE
Multiple command-lines and lists

### ISSUE THREAD

**Issue by kghosesbg** [docopt/docopt#276]
The following command-line definition

```
Usage:
    myprog type1 <file>
    myprog type2 <file>...

Options:
    type1           file should be a single string
    type2           file should be a list of strings
    <file>           file name(s)
```

Results in `args['<file>']` being a list for both `type1` and `type2`. I would have expected the correct behavior to be that `args['<file>']` is a list only for `type2`

Thanks!
-Kaushik

**Comment by keleshev** [comment]
This works as expected. Docopt promotes `<file>` argument to the most general type that is necessary to hold possible values.
