### ISSUE TITLE
Docopt to MAN and later to FISH

### ISSUE THREAD

**Issue by Semyazz** [docopt/docopt#277]
Is it possible to somehow generate MAN pages from `--help` generated by docopt? My ultimate goal is to generate completion for FISH and from what I've seen Fish parses MAN pages.

I've tried cli2man, didn't work. Any other ideas? It'd be awesome to get both nice help in command line and MAN page.

**Comment by tobimensch** [comment]
If cli2man didn't work, why don't you file an issue on the github page of cli2man? I'm the maintainer and I can't fix problems that people don't report. :-)

**Comment by blueyed** [comment]
Has this been fixed / reported to cli2man?

**Comment by tobimensch** [comment]
No it was not reported. So I still have no idea, what the problem may have been.

Actually, if fish parses man pages, the problem could be that cli2man generates man pages
that are using mdoc macros (which are commonly used on BSD systems, but not GNU systems, but are supported by GNU tools nevertheless).

Luckily there's an excellent mdoc to man macro converter in mandoc. cli2man has static packages for mandoc in its repository. It's not unlikely that @Semyazz could have solved his problem in that way. He could have read cli2man's README.md to get that idea himself!

But that's only my wild speculation as to what the issue might be. Generally, please report issues about cli2man at https://github.com/tobimensch/cli2man/issues and not here.

**Comment by Semyazz** [comment]
Sorry I've not replied for a pretty long time. In fact I dropped my script and later FISH itself, because of annoying POSIX incompatibilities. However, I feel I should've check it earlier, so I quickly checked some example code I had with docopt and cli2man and indeed it works like a charm.
