### ISSUE TITLE
Unable to implement use case:

### ISSUE THREAD

**Issue by TiredSounds** [docopt/docopt#300]
Usage: foo.py (<bar> | (one or more options without duplicates) )

    Correct:

    foo.py bar
    foo.py -baz
    foo.py -baz -qux

    Not correct:

    foo.py bar -baz
    foo.py -baz -baz
    foo.py

Perhaps I am missing something, but as soon as I try to implement this using `[]`, the entire statement becomes optional so that calling `$ foo.py` goes through, which is not what I need.

**Comment by TylerTemp** [comment]
Can you give us the exact message you pass to `docopt` and your command line?

I don't get your idea :(

**Comment by TiredSounds** [comment]
Well at the moment I have:

    tips.py (list|graph) (<date> | (-d N -w N -m N -y N)) to (<date> | (-d N -w N -m N -y N))

And from the shell:

    $ tips.py graph -d1 -m1 to 2015-12-17
    $ tips.py list 2014-12-17 to 2015-12-17
etc..

The options -d1 etc are indicating the date by however many units of time ago. With the implementation above however the user is required to use every option mentioned e.g. `-d1 -w1 -m1 -y1` which isn't convenient.

Does that clarify things a little?

**Comment by TylerTemp** [comment]
Maybe the reason is `(-d N -w N -m N -y N)`

For `()`, the elements inside it must appear together, so `-d`, `-w`, `-m`, `-y` must all appear in the command line, `-d1 -m1` fails

`[]` may be the right way.

```
Usage:
    tips.py (list|graph) (<date> | [-d N -w N -m N -y N]) to (<date> | [-d N -w N -m N -y N])

Options:
  -d N
  -w N
  -m N
  -y N
```

**Comment by TiredSounds** [comment]
Ah yes, this is what I was trying to explain haha. 

Using `[]` solves this issue, but at the cost of making everything optional. So using `[]` means that `$ tips.py graph` or `$ tips.py list` are accepted as valid.

**Comment by TylerTemp** [comment]
It seems `docopt` does not provide this kind of validation.

You may see this [example](https://github.com/docopt/docopt/blob/master/examples/validation_example.py)

**Comment by TiredSounds** [comment]
I see, I will look into that thanks.
