### ISSUE TITLE
It doesn't work with indentation by tabulation

### ISSUE THREAD

**Issue by Liliad** [docopt/docopt#312]
Hi,
 Docopt is a very nice module for manage argument in python, thanks for the job.
But a big problem come for me, and after research it appears than docopt work differently if options line are indented by space or by tabulation..

I show you an exemple:
https://gist.github.com/Liadrim/58645221c698748fe726

The two options text are identical, except by the space/tabulation indentations, the result is:
python prog.py -t 10 -s TA
{'--help': False,
 '--special': 'TA',
 '--test': '10',
 '--version': False}
####################################
{'--help': False,
 '--special': None,
 '--test': None,
 '--version': False,
 '-h': False,
 '-s': True,
 '-t': True,
 'TAG': '10',
 'VAL': 'TA'}

With the part before the ### is indented with space and the other part is indented with tabulation.

Is it a know issue ?
Is it possible to correct that ?

Thanks a lot !

**Comment by TylerTemp** [comment]
Note: This is actually fixed in the Github version.

```bash
pip uninstall -y docopt; pip install git+git://github.com/docopt/docopt.git
```
 And then it will work as expected.

**Comment by Liliad** [comment]
Okay nice, thanks for your answer !
