### ISSUE TITLE
Port of docopt to F#

### ISSUE THREAD

**Issue by Aksamyt** [docopt/docopt#315]
Hello,

I have made a port of docot for F# [here](https://github.com/Aksamyt/docopt.fs)!
It is stable and can be used in real world projects, but the API may change a lot until the 1.0 release.

Of all the tests, I chose to remove the ones who tests how the results are returned. Returning null (and using) null is not common in the F# world, so everything returns a value for pattern matching.
Except those two or three, all of them are successful and the test script can be found in [Build/Tests/TestCases/TestCases.fs](https://github.com/Aksamyt/docopt.fs/blob/master/Build/Tests/TestCases/TestCases.fs)

Can you add me and this project to the organization?

Thanks!

**Comment by voieducode** [comment]
Hey well done! @keleshev  usually does the org thing, I will do it this weekend if he does not pick this up.

**Comment by keleshev** [comment]
@Aksamyt how about a type provider API? Great work! 

I'll add the repo to the org tomorrow.

**Comment by Aksamyt** [comment]
@keleshev yeah that’s my priority, that small start up lag hate is growing on me :stuck_out_tongue: 

Thanks! May I close the issue?

**Comment by keleshev** [comment]
@Aksamyt I added you to the docopt organization. I think you can move the repo now. Should we name the repo `docopt.fs`?

**Comment by Aksamyt** [comment]
@keleshev All done! I transferred the repo as `docopt.fs`
