### ISSUE TITLE
Versioning docopt and other ports of docopt

### ISSUE THREAD

**Issue by jaredgrubb** [docopt/docopt#343]
Some people have asked the docopt.cpp to create tags for references to release versions, however the docopt version is currently 0.6.1, which makes it hard to create a subversion for our port (to go to 0.6.1.1 or 0.6.1a or 0.6.1.20160901 or?).

I'd like to suggest that "0.6" be considered the cross-language version that we all try to conform to and that "0.6.x" is reserved for each implementation to rev bugs or adjustments in the implementation.

This issue doesn't really represent a "TODO" for this repo but I wanted to open up the dialogue.

**Comment by insomniacslk** [comment]
Any chance to have this looked at?

**Comment by keleshev** [comment]
Ok with me.
