### ISSUE TITLE
Print help to standard error

### ISSUE THREAD

**Issue by JoanPeturPetersen** [docopt/docopt#352]
When the usage message is printed to the terminal it is printed to the standard output. I don't think this is normal Unix practice. Normally standard error is used for this - look at `grep` as an example.

Normally this does not pose any problem, but can be quite annoying when directing the standard output, for example when piping processes together. Here you wouldn't expect the usage description being passed down the pipe if there is an error in the arguments of any of the the programs.

**Comment by keleshev** [comment]
I just tried `grep --help` and it prints to stdout. Tried `ls --help`, `make --help`, `svn --help`—they do as well. POSIX doesn't seem to say anything on this:

http://pubs.opengroup.org/onlinepubs/007908799/xbd/utilconv.html

If you can take a representative sample of programs and show that `--help` printed to stderr is a dominant behavior, we can consider this.

**Comment by JoanPeturPetersen** [comment]
Hi Vladimir,

thank you for the response. It is true that I can not see anything about the usage message having to be printed to the standard error, `stderr`,  in the document that you linked to. I thought that printing the usage message to `stderr` was the most used way, but now that I've looked more into it, I found that it often depends on the exit code of the program.

On my computer running OS X `grep 2> error.txt` gives a non-zero file, while `grep 1> error.txt` gives a zero sized file. I found the same behaviour on Debian. So in this case the usage message is printed to the standard error. Here grep will fail because it is used in a incorrect way, and will send the usage message to `stderr`.

On the other hand if I try `grep --help 2> error.txt` it gives an empty file. So in this case the usage is written to `stdout`. So `grep` prints the usage message to `stderr` only if there is an error. If you specifically ask for help to be shown, it is written to `stdout`.

The same is true for `ls --foobar 2> err.txt` where the usage message is written to `stderr`.

It can also be seen in the source code for `grep` that is prints the usage message to `stderr` if there is a problem, otherwise `stdout`: [http://git.savannah.gnu.org/cgit/grep.git/tree/src/grep.c#n1901](http://git.savannah.gnu.org/cgit/grep.git/tree/src/grep.c#n1901)

The same seems to be the case for sed: [http://git.savannah.gnu.org/cgit/sed.git/tree/sed/sed.c#n111](http://git.savannah.gnu.org/cgit/sed.git/tree/sed/sed.c#n111)

`git` also prints usage errors to `stderr`: [https://github.com/git/git/blob/master/git.c#L126](https://github.com/git/git/blob/master/git.c#L126)

`locate` will likewise print the usage message to either `stderr` or `stdout` depending on the exit code:
[http://git.savannah.gnu.org/cgit/findutils.git/tree/locate/locate.c#n1387](http://git.savannah.gnu.org/cgit/findutils.git/tree/locate/locate.c#n1387)

**Comment by keleshev** [comment]
That's what docopt does as well, if you pass `--help` it prints (full) usage to stdout with exit code 0, if you pass something erroneous like `--fobar` then it prints (short) usage to stderr with exit code 1.

**Comment by JoanPeturPetersen** [comment]
Yes, I can see that now. So it works correctly - sorry about that.
