### ISSUE TITLE
Pass-through options

### ISSUE THREAD

**Issue by surkova** [docopt/docopt#353]
I am re-writing a command line tool that is on the abstract level is supposed to work like this (doc from main.py):
```
Usage:
    my_tool <command> [<args>...] [options]
```
I have a limited set of commands and each of them may take positional arguments and options. 

Given the limited set of commands I wanted to route them to the modules that contain "real" usage parser, like so (mapping to class methods is intentionally omitted):
```
class Proxy(object):
    """
    Usage: my_tool proxy <stats> [--host=HOST]
    """
    def cmd_stats(host="localhost"):
        pass
```

My problem now is that `my_tool <command> [<args>...] [options]` doesn't parse arbitrary options to pass them through to another parser unless they are specified in the `Options:` section. However, main.py isn't supposed to know all the options the underlying modules might take.

Is there a way to have an abstract options parser?

**Comment by keleshev** [comment]
Take a look at the git example: https://github.com/docopt/docopt/tree/master/examples/git

It's using `options_first=True` to achieve what you want.

**Comment by surkova** [comment]
@keleshev not exactly. what I meant was allowing arbitrary options without having to specify what they are and receiving a dict `{"options": {"first-option": 1, "second_option": 2}}` back after parsing. Basically `[options]` wouldn't have any validations, but further down the chain I could potentially have validation for each command.

**Comment by keleshev** [comment]
In the Git example, when you pass `git add --dry-run file.py` it first is first interpreted by `git.py` with the following usage (simplified):
```
usage: git [--version] [--help]
           <command> [<args>...]
```

Because docopt is run with `options_first=True`, it interprets `--dry-run` as an argument, not option, because it follows an argument/command `add`. Thus you can pass `<args>` further to `git_add.py` with the following usage:

```
usage: git add [options] [--] [<filepattern>...]

options:
  --dry-run
  ...
```

Where `--dry-run` is finally interpreted as an option.

This is not exactly the behavior you want, but wouldn't it allow you to achieve the same result?

**Comment by surkova** [comment]
I see your point. I still don't think passing options as `<args>` is a very straightforward solution and it's pretty misleading when you read the doc. 

In my project we ended up with having a decorator that would parse `__doc__` to register commands as blueprint (~ like Flask does it) and then generating the initial doc (in your example you would have to modify `git.py` manually every time you add a subcommand).
