### ISSUE TITLE
Incorrect parsing of commands with duplicate words

### ISSUE THREAD

**Issue by chakshuahuja** [docopt/docopt#373]
Not sure if it is the desired behavior,
I tried doing (just an example)
`tool folder ls`
I want this command to list all folders in my db.
`tools folder ext ls <folder_id>`
I want to list all extensions of files in that folder.

The second command basically returns me the output of first command followed by second command.

**Comment by keleshev** [comment]
Hi @chakshuahuja, could you provide some more details?
