### ISSUE TITLE
Support setting usage error exit status

### ISSUE THREAD

**Issue by AloisMahdal** [docopt/docopt#375]
Currently it's not (to my knowledge) possible to easily control what exit status your script will end with in case of usage errors.

That is, if I have a convention that usage errors should always propagate as exit status 2 (this is inspired by grep(1)) I should be able to implement that without need to add too much complexity.

For example, this (Python) code:

    args = docopt.docopt(__doc__, version=__VERSION__, exit=2)

would mean that in case my script gets called with invalid combination of arguments, the exit status of my script will be 2 (ie. value of *exit* parameter).

**Comment by AloisMahdal** [comment]
I took a peek at docopt.py to see if I could come up with PR, and relevant part of the code seems to be this (starts around line 20):

    class DocoptExit(SystemExit):

        """Exit in case user invoked program with incorrect arguments."""

        usage = ''

        def __init__(self, message=''):
            SystemExit.__init__(self, (message + '\n' + self.usage).strip())


Frankly I expected `sys.stderr.write()` and `sys.exit()`, which would make the change simple; however the current solution surprised me. My guess is that the justification is that this way the exit event can be easily accompanied with the explanation so that if code surrounding `docopt()` catches this, it can access the message.

I can't come up with solution that would not break things, though.

As a workaround, this works:

        try:
            args = docopt.docopt(__doc__, version=__VERSION__)
        except DocoptExit as e:
            sys.stderr.write(e.message + '\n')
            sys.exit(2)
        else:
            App.main(args)  # or something like that

(althought it does not satisfy my "without need to add too much complexity" wish).

**Comment by keleshev** [comment]
Your workaround is exactly how docopt is supposed to be used in this situation. That is why docopt subclasses SystemExit—in order to be able to catch it and alter the behavior, like exit code, for example.
