### ISSUE TITLE
Multiple optional short options with arguments break the parser

### ISSUE THREAD

**Issue by fwilson42** [docopt/docopt#379]
Sorry for the awful title, what I'm describing is probably best demonstrated with an example. Also, my apologies if this is a duplicate -- I couldn't find anything with a quick look through the issue tracker. Anyway, here's a minimal working example script, Good Utility:

```py
"""Good Utility. Maybe the best utility.

Usage:
    goodutil <a> [-b <bvalue>] [-c <cvalue>]
"""

from docopt import docopt
print(docopt(__doc__))
```

In several cases this works fine, like when none of the optional arguments are specified. Calling the test script with `goodutil a` correctly sets `'<a>': 'a'` in the arguments dict returned from docopt, and everything else is `False` or `None` as expected. Things parse correctly when specifying both `bvalue` and `cvalue` in the right order too, like `goodutil a -b b_value -c c_value`, or when only a bvalue is specified.

Things start to get strange, however, when passing only a cvalue:

```
% python goodutil.py a -c c
{'-b': False,
 '-c': True,
 '<a>': 'a',
 '<bvalue>': 'c',
 '<cvalue>': None}
```

Similar behavior can be seen when passing the arguments out of order, like `a -c c -b b`.

I've tried docopt-0.6.2 from pypi, as well as installing directly from a git clone.

I'm not sure if this is even a bug; the spec in the readme seems a little fuzzy on this. Any ideas?

**Comment by TylerTemp** [comment]
This is because

```
Good Utility. Maybe the best utility.

Usage:
    goodutil <a> [-b <bvalue>] [-c <cvalue>]
```

But `docopt` won't understand that `<bvalue>` belongs to `-b`.

So, to avoid ambiguous, `docopt` will treat `-b` as a stand-alone flag.


To achieve what you want, you need to specific it in options

```
Good Utility. Maybe the best utility.

Usage:
    goodutil <a> [-b <bvalue>] [-c <cvalue>]

Options:
    -b <bvalue>
    -c <cvalue>
```

**Comment by fwilson42** [comment]
Thanks, this works, and now I understand the documentation on the options section more :)
