### ISSUE TITLE
Seems like this is supported, but I can't get multiple arguments to work

### ISSUE THREAD

**Issue by colinta** [docopt/docopt#38]
This is the docstring for [punt](https://github.com/colinta/punt).

I would like to have multiple `--watch` options, but I can't figure out a syntax that supports it.

``` python
"""Watches current path (or another path) for changes and executes
command(s) when a change is detected.  Uses watchdog to track file changes.

Usage:
    punt [-w <path> ...] [-l] [--] <commands>...
    punt (-h | --help)
    punt --version

Options:
    -w <path> ..., --watch <path> ...  Which path to watch [default: current directory]
    -l, --local                        Only tracks local files (disables recusive)
"""
# blablabla
arguments = docopt(__doc__, version='punt v1.6')
print repr(arguments)
```

``` shell
> punt -w dir1 dir2  -- make
{'--': False,
 '--help': False,
 '--local': False,
 '--version': False,
 '--watch': 'dir1',
 '-h': False,
 '<commands>': ['dir2', '--', 'make']}

> punt -w dir1 -w dir2  -- make
{'--': True,
 '--help': False,
 '--local': False,
 '--version': False,
 '--watch': 'dir2',
 '-h': False,
 '<commands>': ['make']}
```

**Comment by sevaivanov** [comment]
In [one](https://github.com/sevaivanov/tcpviewer/blob/master/src/run.py) of my projects, I tried to use this feature with the -e option in the following line:

    script.py [-v] (-i) <interface> [-e <ip> -c] ((-h) <directory> | (-f) <frontend> (-a) <address>)

So it looks like:

    script.py [-v] (-i) <interface> [-e <ips> ... -c] ((-h) <directory> | (-f) <frontend> (-a) <address>)

I also tried:

    script.py [-v] (-i) <interface> [-e <ips> ...] [-c] ((-h) <directory> | (-f) <frontend> (-a) <address>)

Unfortunately, it does not works. Any suggestions?
