### ISSUE TITLE
Changes in Regular Expression Flags since Python Version 3.6

### ISSUE THREAD

**Issue by wirthual** [docopt/docopt#387]
Hello,
thanks for this great project.

I am using it with python 3.6.2 and the Flags for the regular expressions changed (See: https://docs.python.org/3/library/re.html - Changed in version 3.6: Flag constants are now instances of RegexFlag, which is a subclass of enum.IntFlag.)

So instead of using re.I we need to use re.RegexFlag.I.

Hope this helps.

**Comment by winni2k** [comment]
Is this still an issue? 

docopt seems to work ok for me on python 3.6.2?

**Comment by wirthual** [comment]
I just checked the last commits of the re module here:
https://github.com/python/cpython/commits/v3.6.2/Lib/re.py

They did some changes but from my understanding it shouldn't affect the usage of the flags. Maybe I was doing something else wrong. 

I just checked with 3.6.3 and it worked just fine. So from my side this can be closed.

**Comment by winni2k** [comment]
I can't close the issue, so it's all you...
