### ISSUE TITLE
How can I provide default value pragmatically

### ISSUE THREAD

**Issue by starlton-eb** [docopt/docopt#389]
First, I will say that I am pretty new to python so forgive me if obvious. I've been trying to use this in place of bash parsing technique I've used where when displaying help and some arguments are optional if a corresponding environment variable is set, I will display its current value in the help as what will be used by default if argument is not given, example:
```
cat << EOF
Usage:
  ${script} [-e <env>] [-r <region>]

Options:
    -e  --env <env>
      Name of environment that will be used. 
      Optionally set by environment variable TF_VAR_env (currently: '${TF_VAR_env}')

    -r --region <region>
      Name of region that will be used. 
      Optionally set by environment variable TF_VAR_region (currently: '${TF_VAR_region}')
EOF
```
Is it possible somehow to do this with docopt? I would have thought I could possibly define a placeholder for the default value and then pass when instantiating docopt or something similar.

**Comment by winni2k** [comment]
Is this issue still alive, or can it be closed @starlton-eb?

**Comment by starlton-eb** [comment]
I used a different approach so you can close this. Thanks for checking.

**Comment by winni2k** [comment]
@mboersma, @keleshev it looks like this issue can be closed.
