### ISSUE TITLE
Typo on pypi index page

### ISSUE THREAD

**Issue by Sembrani** [docopt/docopt#392]
Not sure where to edit / put in a pull request to edit the pypi page at https://pypi.python.org/pypi/docopt/
The "Porting docopt to other languages" section has a misspelling of "following" as "follosing"

**Comment by winni2k** [comment]
Looks like the 0.6.x branch is where the README.rst for the current release lives.

**Comment by winni2k** [comment]
@mboersma, I think this issue can be closed now.
