### ISSUE TITLE
Optional global parameter

### ISSUE THREAD

**Issue by prsolucoes** [docopt/docopt#395]
Im trying enable a optional parameter for all commands that i have, instead of specify for each available command.

Example is (-d or --debug) that will be available for all commands. It will be enable debug mode. But it is not working. Only work if i specify on each command that it exists. But put all optionals for all commands that i have in my tool is a pain. Can anyone help me?

```
EzoRed

Usage:
 ezored dependency list
 ezored dependency update
 ezored target list
 ezored hello
 ezored -h | --help
 ezored [-d | --debug]

Options:
 -h --help           Show this screen.
 --version           Show version.
 -d --debug          Enable debug messages.
```

If i call:
ezored -d

works, but is not what i want
if i call:
ezored dependency list -d
or
ezored dependency list --debug

dont work
Please. Help.

**Comment by TylerTemp** [comment]
```
EzoRed

Usage:
 ezored [options] dependency list
 ezored [options] dependency update
 ezored [options] target list
 ezored [options] hello
 ezored [options] -h | --help
 ezored [options] [-d | --debug]

Options:
 -h --help           Show this screen.
 --version           Show version.
 -d --debug          Enable debug messages.
```

**Comment by prsolucoes** [comment]
Hi, thanks. It is working.
