### ISSUE TITLE
Transfer this project to Jazzband?

### ISSUE THREAD

**Issue by benjaoming** [docopt/docopt#396]
With all respect! :)

Given the number of unmerged PRs, and the otherwise great quality of the codebase, I would propose that the owners of this repo try to transfer everything to https://github.com/jazzband -- see also https://jazzband.co/

**Comment by SeeSpotRun** [comment]
I agree something is needed.  Either a more actively maintained fork as you suggest, or (preferably) appoint a larger committee of maintainers for https://github.com/docopt/docopt

**Comment by benjaoming** [comment]
@SeeSpotRun - It wouldn't be a fork, it would be a transfer of the docopt repo to the Jazzband organization so its new location would be `github.com/jazzband/docopt`

**Comment by benjaoming** [comment]
Moving to Jazzband is *exactly* to have a larger committee of maintainers, not a fork.

**Comment by SeeSpotRun** [comment]
Honestly I can't see docopt's originator letting go.  So that leaves the option of either convincing @keleshev et al to appoint some extra maintainers that are willing to resolve/close the 177 outstanding issues & 29 open PR's, or else just fork it and move on.

Also https://github.com/docopt has a much wider scope than just python, which is the main reason I think the first option would be preferable.

**Comment by benjaoming** [comment]
> Also https://github.com/docopt has a much wider scope than just python, which is the main reason I think the first option would be preferable.

Yes, it would be strange to "let go" of the original project and let the descendants dangle behind. But I don't think it would do much harm, considering how docopt (for Python) seems quite feature stable.

**Comment by BurntSushi** [comment]
Yeah, I disagree with just transferring this repository. Docopt is first and foremost a specification, with this repository serving as the reference/flagship implementation. But the docopt organization contains many other implementations as well. Moving the reference implementation out while leaving the rest behind doesn't feel right to me.

With that said, if our choices are "no maintenance" and "transfer to jazzband," them I would take the latter. But I think adding maintainers to this repository without moving it is most preferable.

**Comment by benjaoming** [comment]
> With that said, if our choices are "no maintenance" and "transfer to jazzband"

I can't say when that choice becomes true. But during 6 months, 3 easy Travis-related PRs and a typo PR got merged.

Of course, the PR stream is drying out... nobody wants to do PRs on a project that looks dead.

**Comment by benjaoming** [comment]
Everyone agrees that adding maintainers is a great idea, huzzah!
