### ISSUE TITLE
Does docopt support string argument?

### ISSUE THREAD

**Issue by leafonsword** [docopt/docopt#398]
for example:
```
foo.py --sql='create database test'
```
Does docopt support this?

**Comment by TylerTemp** [comment]
This actually depends on the cli tool itself. `docopt` does not have any code handle this situation separately.

```
$ cat args.py 
import sys
print(sys.argv)
$ python args.py --sql='create database test'
['args.py', '--sql=create database test']

```

In this case, `docopt` tread `create database test'` as a whole argument to `--sql`

**Comment by leafonsword** [comment]
@TylerTemp 
Thx，docopt did support string argument~
