### ISSUE TITLE
Options with default arguments: Allow flag without argument?

### ISSUE THREAD

**Issue by GuySmily** [docopt/docopt#406]
Hello,
It's my first time using docopt and writing a tool with formal command like arguments.  Not sure how best to make this clear.. Say I have:

`Options:`
`  -i FILE, --input=FILE        For pre-defined user input. [default: input.file]`

If the user doesn't specify `-i`, then I want `['--input']` to be `None` (so I know not to look for a file)
If the user says `-i` but doesn't specify a file, I want `['--input']` to default to `'input.file'`
If the user specifies a file as in `-i my.file`, then I want `['--input']` to give me `'my.file'`

Right now, if the user says `-i`, the program stops with `-i requires argument` even though a default is in the doc.  But if the user leaves off `-i` completely, then the default value gets assigned to `['--input']`.  Feels backwards to me, but maybe that's because I am new to this.

What's the right way to accomplish what I want?  Or should I just be stricter on users and force them to specify filenames?  Ideally I would put square brackets around the argument, like this, and the default only applies if the flag is specified:
`Options:`
`  -i [FILE], --input[=FILE]        For pre-defined user input. [default: input.file]`

I will have 3 optional flags/files like this btw.  Using optional arguments with defaults, perhaps in combination with flags, doesn't seem like it would work well for more than 1 or 2 inputs (how do you know which of the 3 variables the user intended to specify?  It can be specified with flags, I suppose).

Thanks!
(edit- Even with backticks, it seems newlines and multiple spaces are ignored.  Odd.)

**Comment by SeeSpotRun** [comment]
I think you are stuck needing two options to make this work, e.g.:
```
Options:
-i                        Use input file
-f FILE, --inputfile FILE  Specify custom filename for input file. [default: input.file]

**Comment by GuySmily** [comment]
Nice suggestion.  That meets my needs, Thanks.

**Comment by SeeSpotRun** [comment]
You're welcome.
Maybe you can close the issue now please.

**Comment by GuySmily** [comment]
Hopefully a feature is added in the future that is better than this workaround, but for now I think it's fine to close.

**Comment by SeeSpotRun** [comment]
> Hopefully a feature is added in the future

So desired behaviour for:
```
Usage: foo [Options]
Options:
-i [FILE], --input[=FILE] For pre-defined user input. [default: input.file]
```
is:
```
$ foo               # gives args['--input']=None
$ foo -i            # gives args['--input']='input.file'
$ foo -i input2.file   # gives args['--input']='input2.file'
```

The problem comes if there are also positional arguments:
```
Usage: foo [Options] <file>
Options:
-i [FILE], --input[=FILE] For pre-defined user input. [default: input.file]
```
this creates ambiguity:
```
$ foo target.file
$ foo -i target.file
$ foo -i input2.file target.file
```
How does `docopt` distinguish between optional keyword arguments and positional arguments?

**Comment by GuySmily** [comment]
A conundrum indeed.  I haven't had the chance to implement positional arguments, but in your example the ambiguity is definitely problematic
