### ISSUE TITLE
Problem with parsing arguments: script [ARG1] ARG2

### ISSUE THREAD

**Issue by OnkelTem** [docopt/docopt#425]
A definition like this:
```
Usage:
  script [ARG1] ARG2
```
doesn't produce working configuration. E.g. this doesn't work:
```
$ ./script asd
Usage:
  script [ARG1] ARG2
```
while `asd` should be assigned to `ARG2` according to the definition.

**Comment by TylerTemp** [comment]
docopt using greedy match, and does not support this way
