### ISSUE TITLE
How to assign default values to arguments?

### ISSUE THREAD

**Issue by OnkelTem** [docopt/docopt#426]
For a definition like this:
```
Usage:
  init DECK [TEMPLATE] 

Options:
  DECK                   The name of a deck to initialize.
  TEMPLATE               Use this template to initialize new deck. [Default: Default]
```
`TEMPLATE` isn't getting assigned the "Default" value for a call list this:
```
$ ./init MyDeck
```
I suspect the reason is wrong argument specification in the `Options` section. But how to properly define arguments then?

**Comment by TylerTemp** [comment]
docopt does not support default value assignment for ARGUMENTs, only OPTIONs
