### ISSUE TITLE
Wrap a full command in docopt arguments

### ISSUE THREAD

**Issue by PertuyF** [docopt/docopt#447]
Hi all!

I am pretty happy with `docopt` so far, it makes developing a CLI really easy and clear most of the time, even for complex commands folding.

Now I would like to create a CLI wrapper around a different command, in order to dispatch this command to a different machine. The idea is somehow similar to what `parallel` does:

```sh
wrapper --warg <warg> "cmd --carg <carg>"
```
With `warg` being an optionnal argument to the wrapper, and `carg` an optional argument to the wrapped command.

**Is there a way to do so using docopt?**

Everything I tried failed as long as the command contains a dashed-option that is not documented. My closest match being:
```
Wrapper.

Usage:
  wrapper [-t | --threads <threads>] <cmd>...
  wrapper -h | --help
  wrapper -v | --version

Options:
  -h --help              Show this screen.
  -v --version           Show version.
  -t --threads <threads> Number of threads to use. [default: 1]
```

```sh
$ wrapper mycmd test 2 -t 4
{
  "--help": false, 
  "--threads": [
    "4"
  ], 
  "--version": false, 
  "<cmd>": [
    "mycmd", 
    "test", 
    "2"
  ]
}

$ wrapper mycmd test 2 --arg
Usage:
  wrapper [-t | --threads <threads>] <cmd>...
  wrapper -h | --help
  wrapper -v | --version
```

**Comment by ebarnhill** [comment]
New here so if you don't mind a couple of dumb questions:
1) is your code example meant to indicate that you are happy with the first result, but not the second?
2) why not use some substitute character for the double-dash on initial input, then when you parse the first round of arguments, substitute a double dash for that character?

**Comment by PertuyF** [comment]
@ebarnhill Yes, it is the output from the [online docopt tester](http://try.docopt.org/?doc=Wrapper.%0D%0A%0D%0AUsage%3A%0D%0A++wrapper+%5B-t+%7C+--threads+%3Cthreads%3E%5D+%3Ccmd%3E...%0D%0A++wrapper+-h+%7C+--help%0D%0A++wrapper+-v+%7C+--version%0D%0A%0D%0AOptions%3A%0D%0A++-h+--help++++++++++++++Show+this+screen.%0D%0A++-v+--version+++++++++++Show+version.%0D%0A++-t+--threads+%3Cthreads%3E+Number+of+threads+to+use.+%5Bdefault%3A+1%5D%0D%0A%0D%0A&argv=) for the usage above. First command works as expected (mycmd, test, 2 are captured as the argument `<cmd>`, but as long as you give an option that is not documented, docopt parser will raise an error and return the help.

You're right actually, I could use the double-dash to segregate the `<cmd>` from the wrapper's command:

```
$ wrapper -t 4 -- mycmd test 2 --arg
{
  "--help": false, 
  "--threads": [
    "4"
  ], 
  "--version": false, 
  "<cmd>": [
    "--", 
    "mycmd", 
    "test", 
    "2", 
    "--arg"
  ]
}
```

But I was hoping to capture options from the command as the wrapper's options (like `-t 4`) which will not work:

```
$ wrapper -- mycmd test 2 --arg -t 4
{
  "--help": false, 
  "--threads": [], 
  "--version": false, 
  "<cmd>": [
    "--", 
    "mycmd", 
    "test", 
    "2", 
    "--arg", 
    "-t", 
    "4"
  ]
}
```
Here attributing `-t 4` to the wrapper would require further parsing of `<cmd>`, which goes against the spirit of docopt.

Looks like this is a margin case not suited for `docopt`, I ended using another tool for this case.
