### ISSUE TITLE
repeating keyword arg alias as shortname

### ISSUE THREAD

**Issue by maxnbk** [docopt/docopt#448]
If I do something like:
`usage: tool [options] [--flag=<flag>...]`

I can use multiple repeating args,
but if I add:
`options:
  -f <flag>...  --flag=<flag>... [default: flag1 flag2]`

With the defaults, --flag and -f should be the same list.
But the -f arg receives --flags default as a string and not a list, --flags receives nothing.
I'd like "-f flag" and --flag=flag to simply add up into the same list, and using the same defaults, regardless of whether it ends up in the args dict as the keyword equivalent or short equivalent.

Is there a way to accomplish that both `-f <flag>`... and `--flag=<flag>`... are treated identically?

**Comment by TylerTemp** [comment]
POSIX std says that one option can either expect one argument, or none argument.

Thus, `-f <flag>...` is not std and can not be parsed by docopt correctly.

If you dont mind, docpie can handle this

```python
"""
usage: tool [options] [--flag=<flag>...]

options:
	-f <flag>... --flag=<flag>...    [default: flag1 flag2]
"""

from docpie import docpie

print(docpie(__doc__))
```

which `python tool.py` gives

```python
{'--': False,
 '--flag': ['flag1', 'flag2'],
 '-f': ['flag1', 'flag2']}
```

(though the online test tool of docpie has not been fixed yet... but if you find bug in docpie and issue it, yeah I'll try to fix it)

**Comment by maxnbk** [comment]
Since it's not posix standard to do this, I'll mark this closed, since docopt must adhere to standard. thank you for docpie recommended alternative.
