### ISSUE TITLE
docopt doesn't respect help=False option

### ISSUE THREAD

**Issue by tsturzl** [docopt/docopt#451]
I'm currently setting `help=False` when calling docopt, this ends up printing the help message and exiting even though this isn't what I want, hence why I'm specifying `help=False`. I also don't see `--help` or `-h` in my args when I parse commands. What's even more odd when I specify `help=False` it doesn't display the entire doc it only displays the `Usage`. I take it this is because the command/args entered aren't known. However I still cannot handle `-h --help` myself so it will always fail like this, and if I disable help this isn't something that I want docopt to do.

**Comment by TylerTemp** [comment]
When `help=False`, `docopt` will not handle `-h`, `--help` for you. In this case, whenever you have `-h` or not in your command args, when it does not match any usage case, by default `docopt` will print `Usage` section and exit.

So, in somehow, just `help=False` does not work the way how you think: `help=False` will ignore `-h`, `--help`, but will not change the behavior of `docopt` when no usage case matches your command line argv

**Comment by tsturzl** [comment]
Oh, because I haven't provided it as an option to any of the commands. However I did specify it as an option in general. Had thought that would suffice.
