### ISSUE TITLE
How could my program  ignore docopt when imported as a module?

### ISSUE THREAD

**Issue by leafonsword** [docopt/docopt#454]
I have a progran named `test.py`, it works well in command line environment as a tool using docopt:
```
./test.py -c 4 -p 6
```

And `test.py` has a fuction named `get_host(ip,port)`, I want to use this func in another program, when I try to import :
```
from test import get_host
```
but docopt also shows:
```
Usage:
    test.py -c <thread> -p <port>
```

How could I ignore docopt's parsing when my program is a imported module?

**Comment by TylerTemp** [comment]
```python
"""
Usage: prog [options]

Options:
    -c <thread>
    -p <port>
"""
def my_func(args):
    print("do sth with args, but dont write `docopt` inside this function")

if __name__ == '__main__':
    import docopt
    result = my_func(docopt.docopt(__doc__))
    print(result)
```

**Comment by leafonsword** [comment]
@TylerTemp thx~
