### ISSUE TITLE
Automatically create python wrappers for bash script using docopts

### ISSUE THREAD

**Issue by laurentvm** [docopt/docopt#478]
Hi, 

I have a set of bash script that are now using docopts. I would like to be able to automatically create python function able to call these bash script. 

The idea is the following one. I have a script test.sh with 
```
Usage:
  test.sh (-testdir <testDirPath>) [-v=<VERSION>]
  test.sh -h | --help
Options:
  -h --help         Show this screen.
  -testdir <path>   Dew test directory path.
  -v <version>      Version for XX TOOL [default: Prod].
```

From which I can extract the `Usage` part with grep/sed. Now I want to use docopt to automatically write a python script containing:
```
def test(testdir, v='Prod'):
    subprocess.Popen(['test.sh.sh -testdir %s -v %s' %(testDir, v], shell = True).
```

It seems to be possible to get the arguments from docopt:
```
arguments = docopt(__doc__, version='Naval Fate 2.0')
    print(arguments)
```
but how can I override docopt so it does not try parsing the current python script being executed as what I want is only the arguments dictionnary to buid the function test().
```
from docopt import docopt


with open ("test.doc", "r") as myfile:
    data=myfile.read()
print(data)    
arguments = docopt(data)
```
Any idea? 
Is this thing have been done before?

**Comment by mfekadu** [comment]
Very interesting!

**Comment by frnhr** [comment]
Something like this?

``` python
>>> from docopt import docopt
>>> data = """Foo v. 0.1.2.3.4.5.6.7

Usage:
  foo --bar
  foo --baz=Z

Options:
  -b, --bar        Bar switch.
  -z Z, --baz=ZZZ  Baz value.
"""

>>> docopt(data, argv=["--bar"])
{'--bar': True,
 '--baz': None}

>>> docopt(data, argv=["--baz", "42"])
{'--bar': False,
 '--baz': '42'}
```

**Comment by laurentvm** [comment]
Nope, because in your example, the args are provided and hard coded. What I want is being able to get the dictionnary with typed arguments; default values and so on in order to write (generate) a python wrapper file that defines python function with the correct set of arguments that I can use in python only. 

I can write all the wrapping function myself, by hand but it will request eacht time a manual modifiction if my bash function changes.

**Comment by TylerTemp** [comment]
If I understand it correctly: you want to access the internal data that been parsed and matched by docopt.

In short: nuh, docopt does not expose such api. May considering copy/paste and modify code from docopt.

[My lib](https://github.com/TylerTemp/docpie/blob/master/docpie/pie.py#L777) allows to access parsed data tree (and the matched status, errors, etc), but, I wont suggested it, as it's really nested and complex without document/guid of this part

**Comment by laurentvm** [comment]
Hi Tyler, 

I did try to modifiy docopt to get access to internal data but that was looking to much of an effort for the 15 bash script I have for which I would like a python api. 

Not so simple to do. Thanks for your hints

> If I understand it correctly: you want to access the internal data that been parsed and matched by docopt.
> 
> In short: nuh, docopt does not expose such api. May considering copy/paste and modify code from docopt.
> 
> [My lib](https://github.com/TylerTemp/docpie/blob/master/docpie/pie.py#L777) allows to access parsed data tree (and the matched status, errors, etc), but, I wont suggested it, as it's really nested and complex without document/guid of this part
