### ISSUE TITLE
Unix-style vs. Windows-style options

### ISSUE THREAD

**Issue by surak1961** [docopt/docopt#518]
What do you think of allowing windows style options as well?
In my previous scripts (before I found the marvelous docopt :-)) I allowed using options in both Unix and Windows styles, i.e.
--help | -h | /help | /?
--verbose | -v | /verbose | /v

Or did I miss that the capability already exists?
Regards, Wolfgang

**Comment by Sylvain303** [comment]
Hello @surak1961 

The capability doesn't exists. Mostly coming from Unix world, `/option` doesn't exist. As `/` is folder separator. This would confuse shell completion. 

`docopt` project is stalled. See for fork: https://github.com/docopt/docopt/issues/371

I personally wouldn't encourage usage of `/option` it's confusing. But I don't use windows. So I may be biased. 😉

**Comment by surak1961** [comment]
Thanks for your answer
:-)
